### ISSUE TITLE
Modmaker only working with the first settings used

### ISSUE THREAD

**Issue by D2Aqualung** [tlentz/d2modmaker#113]
I have a question about my modmaker only working with the first settings i put on it, and no others. It says "access denied". When I change the settings, and click run... this happens. 
![Screenshot (2)](https://user-images.githubusercontent.com/68400884/111021757-8af1f800-8383-11eb-8bb8-e1c43e947930.png)

**Comment by OldBeardedCoder** [comment]
From the error message, it looks like d2mm is not able to delete the file data\global\excel\CharStats.txt.  This could be caused by attempting to run d2mm underneath Program Files or Program Files(x86), which later versions of windows does not allow.  I would recommend that you do not install Diablo 2/d2mm to Program Files to avoid this problem.  (And use a short path too, such as c:\d2\
